

mon_executable: main.o
                        gcc -o mon_executable main.o 
main.o: main.c exemple.h 
           gcc -o main.o -c main.c -Wall -Omon_executable: main.o
                        gcc -o mon_executable main.o 
main.o: main.c exemple.h 
           gcc -o main.o -c main.c -Wall -O